// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiPeluqueria.Data.Models;

public partial class Servicio
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public double? Costo { get; set; }

    public bool? EnPromocion { get; set; }

    public virtual ICollection<DetalleTurno> DetalleTurnos { get; set; } = new List<DetalleTurno>();
}